name: social_task
description: "A new Task project for authentication and upload and view image or video."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # required dependencies
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  get: ^4.6.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  flutter_bloc: ^8.1.6
  injectable: ^2.3.2
  get_it: ^7.6.7
  rxdart: ^0.27.7
  logger: ^2.0.2+1
  go_router: ^13.2.0
  firebase_database: ^10.4.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: any
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notoSonts/NotoSans-Thin.ttf
          weight: 300
        - asset: assets/fonts/notoSonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/notoSonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/notoSonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/notoSonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/notoSonts/NotoSans-ExtraBold.ttf
          weight: 800